config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :packs

  root 'landing#index'

  get '/new_pack', to: 'packs#new'
  post '/new_pack', to: 'packs#create'
  get '/my_packs', to: 'packs#index'
  get '/packs/:id', to: 'packs#show'
  get '/packs/:id/edit', to: 'packs#edit'
  post '/packs/:id/edit', to: 'packs#update'
  delete '/packs/:id', to: 'packs#delete', as: 'delete_pack'

  post 'packs/:id', to: 'purchases#create', as: 'purchase_pack'

  get '/catalogue', to: 'catalogues#index'

  get '/account', to: 'account#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    # each category can given to many different packs
    has_many :packs
end

app/models/pack.rb
class Pack < ApplicationRecord
  # each pack is created by one user
  belongs_to :user 
  # each pack must have a category
  belongs_to :category
  # each pack may be purchased by many different users
  has_many :purchases
  # each pack may have many users who have purchased it
  has_many :user_purchases, through: :purchases, source: :user

  # may have and image and a sample file attached
  has_one_attached :image, service: :amazon
  has_one_attached :sample, service: :amazon_sample
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  # user purchasing the pack
  belongs_to :user
  # pack being purchased by the user
  belongs_to :pack
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true

  # sample packs created by the user
  has_many :packs, dependent: :destroy

  # purchases of packs created by other users
  has_many :purchases, dependent: :destroy

  # access to packs created by others users that have been purchased by the current user
  has_many :purchased_packs, through: :purchases, source: :pack
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/account_controller.rb
class AccountController < ApplicationController

    def index
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

        devise_parameter_sanitizer.permit(:account_update, keys: [:username])
    end
end

app/controllers/catalogues_controller.rb
class CataloguesController < ApplicationController

    def index
        # @packs holds only packs the user hasn't created or purchased
        @packs = Pack.all - current_user.packs - current_user.purchased_packs
        
        @category = Category.all
    end

end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  
  def index
  end
  
end

app/controllers/packs_controller.rb
class PacksController < ApplicationController

    def index
      # packs created/owned by the current user
      @my_packs = current_user.packs

      @category = Category.all
      # packs purchased by the current user
      @purchased = current_user.purchased_packs
    end 

    def new
      @pack = Pack.new
      @category = Category.all
    end

    def create
      @pack = Pack.new pack_params
      @pack.user_id = current_user.id
      respond_to do |format|
        if @pack.save
          format.html { redirect_to my_packs_path }
        else
          format.html { render :new }
        end
      end
    end

    def show
      @pack = Pack.find(params[:id])
      @params = params
      @category = Category.all
    end

    def edit
      @pack = Pack.find(params[:id])
      @category = Category.all
    end

    def update
      @pack = Pack.find(params[:id])
        respond_to do |format|
          if @pack.update(pack_params)
            format.html { redirect_to my_packs_path }
          else
            format.html { render :edit }
          end
        end
    end

    def destroy
      Pack.find(params[:id]).destroy
        respond_to do |format|
          format.html { redirect_to packs_url }
        end
    end

    private

    def pack_params
      puts params
      params.require(:pack).permit(:name, :description, :category_id, :price, :user_id, :available, :image, :sample)
    end

     
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

    def create
        @purchase = Purchase.new
        @purchase.user_id = current_user.id
        @purchase.pack_id = params[:id]

        respond_to do |format|
          if @purchase.save
            format.html { redirect_to my_packs_path }
          end
        end
      end

end

app/helpers/account_helper.rb
module AccountHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catalogues_helper.rb
module CataloguesHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/pack_helper.rb
module PackHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/catalogues/index.html.erb
<div class="container">

    <div class="row">
            
        <% @packs.each do |pack|%>
            <% if pack[:available] == true %>
                <div class="col-md-3">
                    <div class="card bg-dark text-white mb-3" style="width: 100%;">
                    <% if pack.image.attached? %>
                        <%= image_tag(pack.image) %>
                    <% else %>
                        <%= image_tag "cover1.jpeg", alt: "Placeholder" %>                       
                    <% end %>
                        <div class="card-body">
                            <h5 class="card-title pack-name"><%= pack.name %></h5>
                            <h6 class="card-subtitle text-right"><%= @category.find(pack.category_id).name %></h6>
                            
                            <%= link_to 'Details', pack_path(pack), method: :get, class:"btn btn-light" %>
                        </div>
                    </div>
                </div>
            <% end %>
        <% end %>

    </div>

</div>

app/views/landing/index.html.erb
<div class="container">
    <div class="jumbotron bg-dark text-light">
        <div class="row">
            <div class="col-md-4">
                <%= image_tag "landing_card.jpg", alt: "MIDI Keyboard", class:"w-100" %>
            </div>
            <div class="col-md-8">
                <h1 class="display-4">Welcome to Sample Share</h1>
                <p class="lead">Share your Sound and Find Inspiration!</p>
                <hr class="my-4">    
                <% if !user_signed_in? %>
                    <%= link_to 'Sign Up', new_user_registration_path, method: :get, class:"btn btn-warning text-dark" %>
                <% end %>     
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sampleshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="//netdna.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="//netdna.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="h-auto">
    <%= render "partials/navbar"%>
    <div class="h-auto p-3 bg-warning text-dark flex-grow-1">
      <p class="alert"><%= alert %></p>
      
        <%= yield %>
      
    </div>
    
  </body>
</html>

app/views/pack/index.html.erb
<div class="row">
        
    <% @my_packs.each do |pack|%>
        <div class="col-md-4">
            <div class="card" style="width: 18rem;">
            <img src="..." class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title"><%= pack.name %></h5>
                    <h6 class="card-subtitle"><%= @category.find(pack.category_id).name %></h6>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
                    <a href="#" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    <% end %>

</div>

app/views/packs/edit.html.erb
<%= render "partials/packs_form"%>

app/views/packs/index.html.erb
<div class="container">
    <h2>My Packs</h2>

    <%# Card listing for the current user's created packs %>
    <div class="row">
    
        <% @my_packs.each do |pack|%>
            <div class="col-md-3">
                <%# class="card-img-top" alt="..." %>
                <div class="card bg-secondary text-white mb-3" style="width: 100%;">

                    <% if pack.image.attached? %>
                        <%= image_tag(pack.image)  %>
                    <% else %>
                        <%= image_tag "cover1.jpeg", alt: "Placeholder" %>                       
                    <% end %>

                    <div class="card-body">
                        <h5 class="card-title"><%= pack.name %></h5>
                        <h6 class="card-subtitle"><%= @category.find(pack.category_id).name %></h6>
                        <p class="card-text"><%= pack.description %></p>
                        <%= link_to 'Details', pack_path(pack), method: :get, class:"btn btn-light" %>
                    </div>
                </div>
            </div>
        <% end %>

    </div><br>
    <%= link_to 'Create New Sample Pack', new_pack_path, method: :get, class: "btn btn-primary" %>
</div>


<div class="container">
    <hr class="my-3">
    <h2>Purchased Packs</h2>
    <br>
    <%# Card listing for the current user's purchased packs %>
    <div class="row">
            
        <% @purchased.each do |pack|%>
            <div class="col-md-3">
                <div class="card bg-secondary text-white mb-3" style="width: 100%;">

                    <% if pack.image.attached? %>
                        <%= image_tag(pack.image)  %>
                    <% else %>
                        <%= image_tag "cover1.jpeg", alt: "Placeholder" %>                       
                    <% end %>

                    <div class="card-body">
                        <h5 class="card-title"><%= pack.name %></h5>
                        <h6 class="card-subtitle"><%= @category.find(pack.category_id).name %></h6>
                        <p class="card-text"><%= pack.description %></p>
                        <%# Button leads to packs#show %>
                        <%= link_to 'Details', pack_path(pack), method: :get, class:"btn btn-light" %>
                    </div>
                </div>
            </div>
        <% end %>

    </div><br>

</div>

app/views/packs/new.html.erb
<%= simple_form_for @pack do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.association :category %>
  <%= f.input :price %>
  <%= f.button :submit %>
<% end %>

app/views/packs/show.html.erb
<div class="container">
    <h1>Show Pack</h1>

    <div class="col-md-4">
        <div class="card" style="width: 18rem;">

            <% if @pack.image.attached? %>
                <%= image_tag(@pack.image)  %>
            <% else %>
                <%= image_tag "cover1.jpeg", alt: "Placeholder" %>                       
            <% end %>

            <div class="card-body">
                <h5 class="card-title"><%= @pack.name %></h5>
                <h6 class="card-subtitle"><%= @category.find(@pack.category_id).name %></h6>
                <p class="card-text"><%= @pack.description %></p>
                
                <%= render "partials/purchase_or_edit_button"%>
            </div>
        </div>
    </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark flex-grow-0">
  <%# Home link %>
  <%= link_to 'Sample Share', root_path, method: :get, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        
        <%# Dropdown Button if signed in. Log In link if user not signed in %>
        <% if user_signed_in?%>
            <%# View My Packs (Owned and Purchased) Link %>
            
            <li class="nav-item">
                <%= link_to 'Catalogue', catalogue_path, method: :get, class: "nav-link" %>
            </li>
            
            <li class="nav-item">
                <%= link_to 'My Packs', packs_path, method: :get, class: "nav-link" %>
            </li>
            
            <%# Dropdown menu for accessing/editing/loggin out of user account %>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu bg-dark" aria-labelledby="navbarDropdown">
                <%= link_to 'Details', account_path, method: :get, class: "nav-link" %>
                <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
                </div>
            </li>

        <% else %>
            <%# Log In link %>
            <li class="nav-item">
                <%= link_to 'Log In', new_user_session_path, method: :get, class: "nav-link bg-warning text-dark" %>
            </li>

        <% end %>
    </ul>
  </div>
</nav>

app/views/partials/_packs_form.html.erb
<div class="container">
  
  <% if current_user.packs.include? @pack %> 
      <h2>Edit Pack</h2>
  <% else %>
      <h2>New Pack</h2>
  <% end %>

  <%= simple_form_for @pack do |f| %>
    <%= f.input :name, required: true %>
    <%= f.input :description %>
    <%= f.association :category, required: true %>
    <%= f.input :price, required: true %>
    <%= f.input :image, as: :file %>
    <%= f.input :sample, as: :file %>
    <%= f.input :available %>
    <%= f.button :submit, class:"btn btn-dark" %>
  <% end %>
  
  <% if current_user.packs.include? @pack %>
    <hr class="my-2"> 
    <%= link_to 'Delete Pack', delete_pack_path, method: :delete, class:"btn btn-danger mt-2", data: { confirm: "Are you sure you want to remove the listing?"}  %>
  <% end %>
</div>

app/views/partials/_purchase_or_edit_button.html.erb
<%# Shows Edit button if the displayed pack was created by the current user %>
<% if current_user.packs.include? @pack %> 
    <%= link_to 'Edit', edit_pack_path, method: :get, class:"btn btn-dark" %>

<%# Shows Download button if the displayed pack has been purchased by the current user %>
<% elsif current_user.purchased_packs.include? @pack %>
    <a href="./test/storage/sample.zip" download class="btn btn-dark">Download</a>
    <%# Download from AWS S3 not available as it is a paid service. However @pack.sample will give the ActiveStorage info from S# of the stored sample. %>
    <p class="card-text">Sample key from AWS S3 <%= @pack.sample %></p>
<%# Shows Purchase button if the displayed pack hasn't been created or purchased by the current user %>
<% else %>
    <p class="card-text">Price $<%= @pack.price %></p>
    <%= link_to 'Purchase', purchase_pack_path, method: :post, class:"btn btn-dark", data: { confirm: "Complete purchase?"} %>

<% end %>